# commons
api:
  prefix : ${API_PREFIX:/api}
spring:
  profiles:
    include:
      - domain
      - common
      - infrastructure
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
springdoc:
  default-produces-media-type: application/json
  default-consumes-media-type: application/json
  swagger-ui:
    tags-sorter: alpha


server:
  servlet:
    context-path: /api
  forward-headers-strategy: framework