spring:
 profiles:
   active: dev

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: ${DEV_DATASOURCE_URL:jdbc:h2:mem:test;MODE=MySQL;DB_CLOSE_ON_EXIT=FALSE}
    driverClassName: ${DEV_DATASOURCE_DRIVER:org.h2.Driver}
    username: ${DEV_DATASOURCE_USERNAME:sa}
    password: ${DEV_DATASOURCE_PASSWORD:}

  jpa:
    database-platform: ${DEV_JPA_DATABASE-PLATFORM:org.hibernate.dialect.H2Dialect}
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
  logging:
    level:
      org:
        hibernate:
          SQL: DEBUG
jwt:
  secret: ${DEV_JWT_SECRET:secret}
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${PROD_DATASOURCE_URL:jdbc:h2:mem:test;MODE=MySQL;DB_CLOSE_ON_EXIT=FALSE}
    driverClassName: ${PROD_DATASOURCE_DRIVER:org.h2.Driver}
    username: ${PROD_DATASOURCE_USERNAME:sa}
    password: ${PROD_DATASOURCE_PASSWORD:}

  jpa:
    database-platform: ${PROD_JPA_DATABASE-PLATFORM:org.hibernate.dialect.H2Dialect}
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  logging:
    level:
      org:
        hibernate:
          SQL: DEBUG
jwt:
  secret: ${PROD_JWT_SECRET:secret}