spring:
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:}
    lettuce:
      pool:
        enabled: on

aws:
  ses:
    access-key: ${AWS_SES_ACCESS_KEY:}
    secret-key: ${AWS_SES_SECRET_KEY:}
    region: ${AWS_SES_REGION:ap-northeast-2}