spring:
  datasource:
    url: ${DATASOURCE_URL:jdbc:h2:~/test;DB_CLOSE_DELAY=-1;MODE=MySQL;DB_CLOSE_ON_EXIT=FALSE}
    username: ${DATASOURCE_USERNAME:sa}
    password: ${DATASOURCE_PASSWORD:}
    driver-class-name: ${DATASOURCE_DRIVER:org.h2.Driver}
    hikari:
      maxLifetime: 580000
      maximum-pool-size: 20
  jpa:
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true
    show-sql: ${SHOW_SQL:true}
    properties:
      hibernate:
        #        format_sql: ${FORMAT_SQL:true}
        default_batch_fetch_size: ${JPA_BATCH_FETCH_SIZE:100}

    sql:
      init:
        mode: always
        continue-on-error: false
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQL8Dialect
    #     script 파일이 hibernate 초기화 이후 동작하게 하기 위한 옵션
    defer-datasource-initialization: false

logging:
  level:
    com.zaxxer.hikari.HikariConfig: DEBUG
    com.zaxxer.hikari: TRACE
    org.springframework.orm.jpa: DEBUG
    org.springframework.transaction: DEBUG
    org.springframework.aop: DEBUG

---

spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:~/test;DB_CLOSE_DELAY=-1;MODE=MySQL;DB_CLOSE_ON_EXIT=FALSE

---

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${DB_NAME:econovation}?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&tinyInt1isBit=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maxLifetime: 580000
      maximum-pool-size: 20
    password: ${MYSQL_PASSWORD}
    username: ${MYSQL_USERNAME}
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        default_batch_fetch_size: ${JPA_BATCH_FETCH_SIZE:100}
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
logging:
  level:
    org.springframework.orm.jpa: DEBUG
    org.springframework.transaction: DEBUG

---

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${DB_NAME}?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&tinyInt1isBit=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maxLifetime: 580000
      maximum-pool-size: 20
    password: ${MYSQL_PASSWORD}
    username: ${MYSQL_USERNAME}
  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: ${JPA_BATCH_FETCH_SIZE:100}
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL8Dialect